'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Download, FileText, Loader2 } from 'lucide-react'

// Simple HTML-to-PDF using print window (works without @react-pdf/renderer for complex layouts)
async function generatePDF(htmlContent: string, filename: string) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    alert('Please allow popups to export PDF')
    return
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1a1a1a; background: #fff; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #7c3aed; }
        .header h1 { font-size: 28px; color: #7c3aed; margin-bottom: 8px; }
        .header p { color: #666; font-size: 14px; }
        .stats { display: flex; gap: 20px; margin-bottom: 30px; justify-content: center; }
        .stat { background: #f5f3ff; padding: 12px 24px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #7c3aed; }
        .stat-label { font-size: 12px; color: #666; margin-top: 4px; }
        .item { padding: 16px 0; border-bottom: 1px solid #eee; page-break-inside: avoid; }
        .item-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
        .item-title { font-weight: 600; color: #1a1a1a; font-size: 14px; }
        .item-date { color: #999; font-size: 12px; }
        .item-url { color: #7c3aed; font-size: 12px; margin-bottom: 4px; word-break: break-all; }
        .item-content { color: #444; font-size: 13px; line-height: 1.6; }
        .item-tags { display: flex; gap: 6px; margin-top: 8px; flex-wrap: wrap; }
        .tag { background: #ede9fe; color: #7c3aed; padding: 2px 8px; border-radius: 4px; font-size: 11px; }
        .item-meta { display: flex; gap: 16px; margin-top: 6px; }
        .meta-item { color: #888; font-size: 11px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 500; }
        .badge-code { background: #d1fae5; color: #065f46; }
        .badge-docs { background: #dbeafe; color: #1e40af; }
        .badge-social { background: #fce7f3; color: #9d174d; }
        .badge-research { background: #e0e7ff; color: #3730a3; }
        .badge-general { background: #f3f4f6; color: #374151; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 12px; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
      </style>
    </head>
    <body>
      ${htmlContent}
      <div class="no-print" style="text-align:center; margin: 30px 0;">
        <button onclick="window.print()" style="background: #7c3aed; color: white; border: none; padding: 12px 32px; border-radius: 8px; font-size: 16px; cursor: pointer;">Download PDF</button>
      </div>
      <div class="footer">Generated by Memora Bond — AI Browser Memory | ${new Date().toLocaleDateString()}</div>
    </body>
    </html>
  `)
  printWindow.document.close()
}

export function ExportPDFButton() {
  const [isExporting, setIsExporting] = useState(false)
  const [exportType, setExportType] = useState<string | null>(null)

  const handleExport = async (type: string) => {
    setIsExporting(true)
    setExportType(type)
    try {
      const token = localStorage.getItem('memora_token')
      const res = await fetch('/api/export/pdf', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ type }),
      })
      const result = await res.json()
      if (!res.ok) throw new Error(result.error)

      const html = buildExportHTML(result)
      await generatePDF(html, `${result.title}.pdf`)
    } catch (error: any) {
      alert('Export failed: ' + error.message)
    } finally {
      setIsExporting(false)
      setExportType(null)
    }
  }

  return (
    <div className="space-y-3">
      <h3 className="text-sm font-medium text-zinc-200 flex items-center gap-2">
        <FileText size={14} className="text-violet-400" /> Export Data
      </h3>
      <div className="grid grid-cols-2 gap-2">
        {[
          { type: 'memories', label: 'Memories', icon: '🧠' },
          { type: 'timeline', label: 'Timeline', icon: '📋' },
          { type: 'sessions', label: 'Sessions', icon: '⏱️' },
          { type: 'all', label: 'Everything', icon: '📦' },
        ].map((item) => (
          <button
            key={item.type}
            onClick={() => handleExport(item.type)}
            disabled={isExporting}
            className="flex items-center gap-2 px-3 py-2.5 rounded-lg border border-zinc-800/50 hover:bg-zinc-800/30 transition-colors text-xs text-zinc-300 hover:text-zinc-100 disabled:opacity-50"
          >
            {isExporting && exportType === item.type ? (
              <Loader2 size={14} className="animate-spin" />
            ) : (
              <span>{item.icon}</span>
            )}
            {item.label}
          </button>
        ))}
      </div>
    </div>
  )
}

function buildExportHTML(result: any): string {
  const { title, exportDate, userName, count, data } = result

  const header = `
    <div class="header">
      <h1>${title}</h1>
      <p>Exported for ${userName} on ${new Date(exportDate).toLocaleString()}</p>
    </div>
    <div class="stats">
      <div class="stat">
        <div class="stat-value">${count}</div>
        <div class="stat-label">Items</div>
      </div>
      <div class="stat">
        <div class="stat-value">${new Set(data.map((d: any) => d.domain || 'unknown')).size}</div>
        <div class="stat-label">Domains</div>
      </div>
    </div>
  `

  const items = data.map((item: any) => {
    const pageTypeClass = item.pageType ? `badge-${item.pageType}` : 'badge-general'
    const date = item.createdAt || item.timestamp || item.startedAt
    const formattedDate = date ? new Date(date).toLocaleString() : ''

    return `
      <div class="item">
        <div class="item-header">
          <div class="item-title">${escapeHtml(item.title || 'Untitled')}</div>
          <div class="item-date">${formattedDate}</div>
        </div>
        ${item.url ? `<div class="item-url">${escapeHtml(item.url)}</div>` : ''}
        ${item.textPreview ? `<div class="item-content">${escapeHtml(item.textPreview)}</div>` : ''}
        ${item.description ? `<div class="item-content">${escapeHtml(item.description)}</div>` : ''}
        ${item.pageType ? `<span class="badge ${pageTypeClass}">${item.pageType}</span>` : ''}
        ${item.domain ? `<span class="meta-item">🌐 ${escapeHtml(item.domain)}</span>` : ''}
        ${item.tags && item.tags.length ? `
          <div class="item-tags">
            ${item.tags.map((tag: string) => `<span class="tag">${escapeHtml(tag)}</span>`).join('')}
          </div>
        ` : ''}
      </div>
    `
  }).join('')

  return header + items
}

function escapeHtml(text: string): string {
  return String(text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
